### ISSUE TITLE
question: remove header

### ISSUE THREAD

**Issue by NovaGL** [KTibow/lovelace-dark-soft-ui-theme#6]
Hi,

I saw you removed the header in your theme and made it transparent. can you advise what part of the code does this.

Thanks!

**Comment by KTibow** [comment]
It's this bit of code:
https://github.com/KTibow/lovelace-dark-soft-ui-theme/blob/main/theme.yaml#L260-L367
Let me know if you have any questions, and consider closing if you're satisfied.

**Comment by NovaGL** [comment]
Thanks. I added that in and it's still not working properly is there some card mod setting I'm missing

**Comment by KTibow** [comment]
Yeah, `--card-mod-theme`, and make sure you've selected the right theme and the themes have been reloaded.

**Comment by NovaGL** [comment]
So if I made a new theme with different colours and called it soft-ui-silver would it then work if I changed card-mod-theme to soft-ui-silver

**Comment by KTibow** [comment]
I think so. But you know there are already different colors? What color do you want?

**Comment by NovaGL** [comment]
I want to do my own experiments as some elements don't look correct eg too much shadow or want to remove borders on certain elements.

Basically I want a lite version of your theme.

**Comment by KTibow** [comment]
@NovaGL You can make something without any card-mod:
```
Light:
  primary-background-color: "#F3F5F7"
  card-background-color: "#F3F5F7"
  paper-card-background-color: "#F3F5F7"
  secondary-background-color: "#F3F5F7"
  divider-color: "#F3F5F7"
  ha-card-border-radius: 15px
  ha-card-box-shadow: -4px -4px 8px rgba(255, 255, 255, .5), 5px 5px 8px rgba(0, 0, 0, .03)
```
Adjust the shadow as needed.
Dark:
```
Dark:
  primary-background-color: "#222"
  card-background-color: "#222"
  paper-card-background-color: "#222"
  secondary-background-color: "#222"
  divider-color: "#222"
  primary-text-color: white
  sidebar-icon-color: white
  ha-card-border-radius: 15px
  ha-card-box-shadow: -5px -5px 8px rgba(50, 50, 50, .2), 5px 5px 8px rgba(0, 0, 0, .08)
```
